//
// Generated file, do not edit! Created by opp_msgtool 6.0 from src/PONMessages.msg.
//

#ifndef __PON_DBA_SIM_PONMESSAGES_M_H
#define __PON_DBA_SIM_PONMESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace pon_dba_sim {

class DataPacket;
class ReportMessage;
class GrantMessage;

}  // namespace pon_dba_sim

// cplusplus {{
#include <omnetpp.h>
using namespace omnetpp;
// }}


namespace pon_dba_sim {

/**
 * Class generated from <tt>src/PONMessages.msg:13</tt> by opp_msgtool.
 * <pre>
 * // Paquete de datos generado por las ONUs (tráfico upstream)
 * // trafficClass=0→verde(eMBB), 1→rojo(URLLC), 2→naranja(mMTC)
 * packet DataPacket
 * {
 *     \@display("i=msg/packet");
 *     int sourceONU;
 *     int trafficClass;       // 0=eMBB, 1=URLLC, 2=mMTC
 *     simtime_t creationTime; // para calcular latencia end-to-end
 *     simtime_t deadline;     // solo URLLC (250us), -1 para otros
 *     int dataSize;           // bytes
 * }
 * </pre>
 */
class DataPacket : public ::omnetpp::cPacket
{
  protected:
    int sourceONU = 0;
    int trafficClass = 0;
    ::omnetpp::simtime_t creationTime = SIMTIME_ZERO;
    ::omnetpp::simtime_t deadline = SIMTIME_ZERO;
    int dataSize = 0;

  private:
    void copy(const DataPacket& other);

  protected:
    bool operator==(const DataPacket&) = delete;

  public:
    DataPacket(const char *name=nullptr, short kind=0);
    DataPacket(const DataPacket& other);
    virtual ~DataPacket();
    DataPacket& operator=(const DataPacket& other);
    virtual DataPacket *dup() const override {return new DataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceONU() const;
    virtual void setSourceONU(int sourceONU);

    virtual int getTrafficClass() const;
    virtual void setTrafficClass(int trafficClass);

    virtual ::omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(::omnetpp::simtime_t creationTime);

    virtual ::omnetpp::simtime_t getDeadline() const;
    virtual void setDeadline(::omnetpp::simtime_t deadline);

    virtual int getDataSize() const;
    virtual void setDataSize(int dataSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/PONMessages.msg:23</tt> by opp_msgtool.
 * <pre>
 * // Reporte de ONU a OLT: cuántos bytes tiene en cada cola
 * message ReportMessage
 * {
 *     \@display("i=msg/report");
 *     int sourceONU;
 *     int queueSize_eMBB;     // bytes pendientes eMBB
 *     int queueSize_URLLC;    // bytes pendientes URLLC
 *     int queueSize_mMTC;     // bytes pendientes mMTC
 * }
 * </pre>
 */
class ReportMessage : public ::omnetpp::cMessage
{
  protected:
    int sourceONU = 0;
    int queueSize_eMBB = 0;
    int queueSize_URLLC = 0;
    int queueSize_mMTC = 0;

  private:
    void copy(const ReportMessage& other);

  protected:
    bool operator==(const ReportMessage&) = delete;

  public:
    ReportMessage(const char *name=nullptr, short kind=0);
    ReportMessage(const ReportMessage& other);
    virtual ~ReportMessage();
    ReportMessage& operator=(const ReportMessage& other);
    virtual ReportMessage *dup() const override {return new ReportMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceONU() const;
    virtual void setSourceONU(int sourceONU);

    virtual int getQueueSize_eMBB() const;
    virtual void setQueueSize_eMBB(int queueSize_eMBB);

    virtual int getQueueSize_URLLC() const;
    virtual void setQueueSize_URLLC(int queueSize_URLLC);

    virtual int getQueueSize_mMTC() const;
    virtual void setQueueSize_mMTC(int queueSize_mMTC);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReportMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReportMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/PONMessages.msg:32</tt> by opp_msgtool.
 * <pre>
 * // Grant de OLT a ONU: slot de transmisión asignado
 * message GrantMessage
 * {
 *     \@display("i=msg/token");
 *     int destONU;
 *     simtime_t startTime;    // inicio absoluto del slot
 *     int grantSize_eMBB;     // bytes autorizados eMBB
 *     int grantSize_URLLC;    // bytes autorizados URLLC
 *     int grantSize_mMTC;     // bytes autorizados mMTC
 * }
 * </pre>
 */
class GrantMessage : public ::omnetpp::cMessage
{
  protected:
    int destONU = 0;
    ::omnetpp::simtime_t startTime = SIMTIME_ZERO;
    int grantSize_eMBB = 0;
    int grantSize_URLLC = 0;
    int grantSize_mMTC = 0;

  private:
    void copy(const GrantMessage& other);

  protected:
    bool operator==(const GrantMessage&) = delete;

  public:
    GrantMessage(const char *name=nullptr, short kind=0);
    GrantMessage(const GrantMessage& other);
    virtual ~GrantMessage();
    GrantMessage& operator=(const GrantMessage& other);
    virtual GrantMessage *dup() const override {return new GrantMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDestONU() const;
    virtual void setDestONU(int destONU);

    virtual ::omnetpp::simtime_t getStartTime() const;
    virtual void setStartTime(::omnetpp::simtime_t startTime);

    virtual int getGrantSize_eMBB() const;
    virtual void setGrantSize_eMBB(int grantSize_eMBB);

    virtual int getGrantSize_URLLC() const;
    virtual void setGrantSize_URLLC(int grantSize_URLLC);

    virtual int getGrantSize_mMTC() const;
    virtual void setGrantSize_mMTC(int grantSize_mMTC);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GrantMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GrantMessage& obj) {obj.parsimUnpack(b);}


}  // namespace pon_dba_sim


namespace omnetpp {

template<> inline pon_dba_sim::DataPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<pon_dba_sim::DataPacket*>(ptr.get<cObject>()); }
template<> inline pon_dba_sim::ReportMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<pon_dba_sim::ReportMessage*>(ptr.get<cObject>()); }
template<> inline pon_dba_sim::GrantMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<pon_dba_sim::GrantMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PON_DBA_SIM_PONMESSAGES_M_H

